version: '3.8'
services:
  web_online_meet_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "14000:14000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge