version: '3.8'
services:
  web_online_meet_frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../app:/app:delegated
      - /app/node_modules:/app/node_modules:delegated
    ports:
      - "14000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge